### ISSUE TITLE
Google API change

### ISSUE THREAD

**Issue by rbu** [terryyin/translate-python#14]
Current version gives a 503. Have a look at:
https://github.com/soimort/translate-shell/commit/8354bbe738419d4b1d6ae00d125fb348f76b692d

**Comment by gomord** [comment]
i am also having the same problem.

**Comment by terryyin** [comment]
oops! right, the API has changed, let me see if there's any new available free APIs.

**Comment by terryyin** [comment]
I've switched to http://mymemory.translated.net/ for now. It's only provide 1000 words/day free requests. Let's see if people still find it useful to use this library. Or there's any better API ...

**Comment by rbu** [comment]
Have you checked the changeset I linked in the original post? The perl script seems to use the new Google API.

**Comment by terryyin** [comment]
Oh, I didn't saw that! Sorry. Let me try it...

**Comment by dnes85** [comment]
hi @terryyin what do you think about integrating Microsoft Translate as well? It provides 7k queries/day for free, so it's better than the current limit. :-)

**Comment by terryyin** [comment]
The new version can support multiple providers now.
