### ISSUE TITLE
 emoji  💡 can not decode

### ISSUE THREAD

**Issue by maaiika** [terryyin/translate-python#27]
```
def transE2C(word):
    translator = Translator(service_urls=[
      'translate.google.com',
      'translate.google.cn',
    ])
    translator = Translator()
    a=translator.translate(word, src='auto' ,dest='zh-cn')
    print(a.text)
    return a.text


transE2C("💡 hi im ok")
```

**Comment by maaiika** [comment]
File "C:\python36\lib\site-packages\googletrans\client.py", line 132, in translate
    data = self._translate(text, dest, src)
  File "C:\python36\lib\site-packages\googletrans\client.py", line 63, in _translate
    data = utils.format_json(r.text)
  File "C:\python36\lib\site-packages\googletrans\utils.py", line 51, in format_json
    converted = json.loads(text)
  File "C:\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by terryyin** [comment]
It’s perhaps because you are using Python 2.7.

Now it seems a frequent problem. Let me put Python 2.7 emoji support with a bit higher priority. Thanks for the report.

**Comment by wesleytao** [comment]
Dude, don't you see python36 in the file path? which means he is using python 3.6  
I met the sample problem

**Comment by terryyin** [comment]
Ok. Reopened this issue. But so far I have no clue why it happened.

**Comment by wesleytao** [comment]
bro, I think this has something to do with the json parsing. Emojis encoded like \U0001f6f9 cannot be handled properly with  jsondecoder:
`---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-97-d5467c6ef9f2> in <module>()
----> 1 trans=translator.translate(text,dest='en',src='auto')
      2 trans.text

~\Anaconda3\lib\site-packages\googletrans\client.py in translate(self, text, dest, src)
    170 
    171         origin = text
--> 172         data = self._translate(text, dest, src)
    173 
    174         # this code will be updated when the format is changed.

~\Anaconda3\lib\site-packages\googletrans\client.py in _translate(self, text, dest, src)
     79         r = self.session.get(url, params=params)
     80 
---> 81         data = utils.format_json(r.text)
     82         return data
     83 

~\Anaconda3\lib\site-packages\googletrans\utils.py in format_json(original)
     60         converted = json.loads(original)
     61     except ValueError:
---> 62         converted = legacy_format_json(original)
     63 
     64     return converted

~\Anaconda3\lib\site-packages\googletrans\utils.py in legacy_format_json(original)
     52             text = text[:p] + states[j][1] + text[nxt:]
     53 
---> 54     converted = json.loads(text)
     55     return converted
     56 

~\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

~\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

~\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by rhenter** [comment]
@wesleytao this does not happened in the current version. Following the example bellow:

```python
In [1]: from translate import Translator

In [2]: translator = Translator(to_lang='zh-cn')

In [3]: a = "💡 Hello I'm ok"

In [4]: print(translator.translate(a))
💡你好，我没事
```
