### ISSUE TITLE
Bad translation depending on uppercase or not

### ISSUE THREAD

**Issue by stephanedebove** [terryyin/translate-python#50]
Hello,

any idea why:

```
from translate import Translator
text = 'Happy new year'
translator= Translator(to_lang='fr')
translated_text=translator.translate(text)
print(translated_text.encode('utf-8')) 
```

gives the correct answer (but in uppercase, why?) : 

`BONNE ANNÉE
`
but the same code with 

`text = 'Happy New Year'
`
outputs 

`Bonne Année,La
`
which doesn't mean anything?

**Comment by terryyin** [comment]
Sometimes the free database is not so great. If it is just several particular mistakes perhaps you can find the translation service (depends on which one do you use) and change it by yourself.
