### ISSUE TITLE
I created a azure translator on the azure portal and I have the api keys. But I get an error when entering the key in the code.

### ISSUE THREAD

**Issue by timsmit97** [terryyin/translate-python#59]
I entered my first api key in the code below:

from translate import Translator as trans
translator = trans(provider='microsoft', to_lang='nl', secret_access_key='xxxxxx')
translation = translator.translate("I am such an amateur in python, I don't even know how to translate this ")
print(translation)

but then I get the following error:
HTTPError: 401 Client Error: Access Denied for url: https://api.cognitive.microsoft.com/sts/v1.0/issueToken

I replaced my api key with xxxxx,  but can anybody explain to me if I entered the right key there?
I took the first key from the 'keys and endpoint' menu in the azure portal.
Or do I have to enter something else here?

**Comment by matze19999** [comment]
same problem here

**Comment by pringon** [comment]
Fix in #63, but only the previous issue was linked correctly
